# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:eess.* OR cat:nlin.*'

# 検索キーワード
keywords:
        design: 5
        interface: 5
        HCI: 5
        human: 3
        kaggle: 3

# 通知の閾値
score_threshold: 0
