# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:eess.* OR cat:econ.*'

# 検索キーワード
keywords:
        3D: 1
        agent: 1
        ambient: 1
        animation: 1
        AR: 1
        augumented: 1
        behavior: 1
        Cognitive Coprocessor: 1
        computational design: 1
        conceptual model: 1
        design: 1
        device: 1
        Fitts's Law: 1
        folksonomy: 1
        gesture recognition: 1
        graphic: 1
        haptics: 1
        HCI: 1
        human computation: 1
        information visualization: 1
        input device: 1
        interaction: 1
        interface: 1
        lifestreams: 1
        mixed reality: 1
        mobile: 1
        multi-touch: 1
        personal informatics: 1
        predictive: 1
        recognition: 1
        social: 1
        tangible: 1
        tuple space: 1
        ubiquitous: 1
        UI: 1
        usability: 1
        user: 1
        virtual reality: 1
        visualization: 1
        voice: 1
        VR: 1
        wearable: 1
        zooming: 1

# 通知の閾値
score_threshold: 3
