# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:eess.* OR cat:nlin.* OR cat:q-fin.* OR cat:econ.*'

# 検索キーワード
keywords:
        design: 5
        interface: 5
        HCI: 5
        interaction: 3
        social media: 3
        user: 3
        mobile: 3
        VR: 3
        virtual reality: 3
        AR: 3
        augumented reality: 3
        personal informatics: 3
        visualization: 3
        wearable computing: 3
        behavior: 3
        human computation: 3
        UI: 3
        computational design: 3
        graphic: 3
        human: 3
        kaggle: 3
        information visualization: 3
        ubiquitous computing: 3
        Fitts’s Law: 3
        Cognitive Coprocessor: 3
        usability analysis: 3
        animation: 3
        zooming: 3
        multi-touch interface: 3
        gesture recognition: 3
        voice recognition: 3
        object recognition: 3
        mixed reality: 3
        tuple space: 3
        lifestreams: 3
        3D interface: 3
        social recommendation: 3
        input device: 3
        tangible interface: 3
        ambient computing: 3
        agent: 3
        conceptual model: 3
        ambient media: 3
        ambient intelligence: 3
        folksonomy: 3
        predictive interface: 3
        graphic: 3



# 通知の閾値
score_threshold: 0
